### ISSUE TITLE
It seem hot reload not work

### ISSUE THREAD

**Issue by azulkipli** [alanbsmith/react-electron-starter#1]
I've tried change Hello to Hi on App.js it seem hot reload not working

**Comment by alanbsmith** [comment]
Did you try manually refreshing? I'm not sure the hot reload works on this starter. The assets _should_ auto-update, but the page doesn't update without a refresh.

**Comment by azulkipli** [comment]
Yes after manually refresh (Cmd+R) the css updated.

**Comment by alanbsmith** [comment]
@azulkipli If you find a way to get hot reloading working and submit a PR, I'd be happy to merge it in. Closing this issue for now.
